window.GAME_CONFIG = {
  id: "tic-tac-toe",
  title: "Tic-Tac-Toe",
  name: "Tic-Tac-Toe",
  description: "Face a class-calibrated computer or challenge another signed-in student through a live five-digit room. Answer a question before each move, then make three in a row.",
  catchphrase: "Three in a row wins the show!",
  genre: "Quiz / Strategy",
  gameModes: ["singleplayer", "multiplayer"],
  primaryMode: "multiplayer",
  players: "1 Player / 2 Online",
  questionType: "host-choice",
  version: "1.0.0",
  entry: "index.html",
  icon: "❎",
  saveKey: null,
  requiresQuestionBank: true,
  supportsHighScores: false,
  supportsAchievements: true,
  createdBy: "Mr McKenzie",
  challengeMode:{enabled:false,types:{}}
};
