(function(){'use strict';
const ID='pixel-artillery',KEY='arcadeAcademy.pixelArtillery.activeMatch',W=800,H=450,GROUND=390;
const $=id=>document.getElementById(id);let me,match,matchId,stop,question,questionNonce,bankKey,session=false,claiming=new Set(),lastShotId=null,single=false,aiThinking=false;
const weapons={cannon:{damage:34,radius:45,ammo:null},heavy:{damage:52,radius:68,ammo:'heavy'},triple:{damage:24,radius:34,ammo:'triple'},rocket:{damage:46,radius:30,ammo:'rocket'},mega:{damage:76,radius:90,ammo:'mega'}};
function terrain(){let a=[],base=270+Math.random()*40,phase=Math.random()*Math.PI*2,freq=1.5+Math.random()*2.5,ampl=55+Math.random()*55;for(let i=0;i<80;i++){let macro=Math.sin(i/10*freq/10+phase)*ampl,micro=Math.random()*32-16,y=base+macro+micro;if(Math.random()<0.07)y+=(Math.random()<0.5?-1:1)*(30+Math.random()*55);y=Math.max(120,Math.min(385,y));a.push(y);}for(let i=1;i<79;i++)a[i]=(a[i-1]+a[i]*2+a[i+1])/4;for(let i=0;i<80;i++)a[i]=Math.round(a[i]);for(let i=0;i<8;i++){a[i]=330;a[71+i]=330;}return a;}
function generateIslands(){let count=2+Math.floor(Math.random()*3),islands=[],attempts=0;while(islands.length<count&&attempts<50){attempts++;let w=55+Math.random()*65,h=20+Math.random()*16,x=110+Math.random()*(W-220),y=65+Math.random()*130;if(islands.some(o=>Math.abs(o.x-x)<(o.w+w)/2+25&&Math.abs(o.y-y)<70))continue;islands.push({x,y,w,h});}return islands;}
function freshState(){return{phase:'ready',terrain:terrain(),islands:generateIslands(),players:{p1:{x:85,hp:100,shield:0,ammo:{heavy:2,triple:2,rocket:2,mega:1}},p2:{x:715,hp:100,shield:0,ammo:{heavy:2,triple:2,rocket:2,mega:1}}},ready:{},moveRemaining:80,turnGate:null,turnDeadline:null,lastShot:null};}
function screen(name){['loading','menu','join','room','game'].forEach(n=>$(n+'-screen').hidden=n!==name)}
function stats(){let s=PlatformManager.getGameStats(ID)||{};$('wins').textContent=s.wins||0;$('losses').textContent=s.losses||0;$('draws').textContent=s.draws||0;$('games').textContent=s.gamesPlayed||0}
async function init(){bind();try{await MultiplayerManager.initialiseAuth();me=await MultiplayerManager.requirePlayer();stats();let saved=localStorage.getItem(KEY);if(saved&&/^\d{5}$/.test(saved))listen(saved);else screen('menu')}catch(e){$('loading-screen').innerHTML='<p>Sign in through the Arcade Academy Hub before playing online.</p><a href="../../index.html">Return to Hub</a>'}setInterval(tick,250);requestAnimationFrame(draw)}
function bind(){$('single-btn').onclick=()=>{$('single-options').hidden=false;$('multiplayer-options').hidden=true};$('multiplayer-btn').onclick=()=>{$('single-options').hidden=true;$('multiplayer-options').hidden=false};$('start-single-btn').onclick=startSingle;$('create-btn').onclick=create;$('show-join-btn').onclick=()=>screen('join');$('join-back').onclick=()=>screen('menu');$('join-form').onsubmit=join;$('room-input').oninput=e=>e.target.value=e.target.value.replace(/\D/g,'').slice(0,5);['leave-room-btn','leave-game-btn','result-leave'].forEach(id=>$(id).onclick=leave);$('ready-btn').onclick=ready;$('left-btn').onclick=()=>move(-20);$('right-btn').onclick=()=>move(20);$('end-btn').onclick=endTurn;$('fire-btn').onclick=fire;$('angle').oninput=e=>$('angle-out').textContent=e.target.value+'°';$('power').oninput=e=>$('power-out').textContent=e.target.value;$('rematch-btn').onclick=rematch}
async function startSingle(){try{let classCode=PlatformManager.getClassCode(),questionType=$('question-type').value;if(!classCode)throw Error('Return to the Hub and enter your class code first.');let loaded=await MultiplayerQuestionHelper.load({classCode,questionType});if(!loaded.ok)throw Error('That question type is unavailable for this class.');let state=freshState();state.phase='playing';state.turnGate={uid:me.uid,status:'pending',nonce:Date.now()+''};match=await SinglePlayerManager.createMatch(ID,state,{questionType},$('ai-difficulty').value);single=true;matchId=match.id;let ai=match.settings.aiProfile;$('ai-summary').textContent=Math.round(ai.averageAccuracy*100)+'% target · '+(ai.source==='class-data'?ai.group+', '+ai.sampleSize+' student sample':'safe fallback');stop=SinglePlayerManager.listen(changed)}catch(e){$('menu-error').textContent=e.message}}
async function create(){try{let classCode=PlatformManager.getClassCode(),questionType=$('question-type').value;if(!classCode)throw Error('Return to the Hub and enter your class code first.');let loaded=await MultiplayerQuestionHelper.load({classCode,questionType});if(!loaded.ok)throw Error('That question type is unavailable for this class.');matchId=await MultiplayerManager.createRoom(ID,freshState(),{questionType,requiresReady:true});localStorage.setItem(KEY,matchId);listen(matchId)}catch(e){$('menu-error').textContent=e.message}}
async function join(e){e.preventDefault();let code=$('room-input').value;if(!/^\d{5}$/.test(code)){$('join-error').textContent='Enter exactly five numbers.';return}try{matchId=await MultiplayerManager.joinRoom(code);localStorage.setItem(KEY,matchId);listen(matchId)}catch(err){$('join-error').textContent=err.message==='ROOM_NOT_FOUND'?'Room not found.':err.message==='ROOM_FULL'?'This room already has two players.':err.message}}
function listen(id){if(stop)stop();single=false;matchId=id;stop=MultiplayerManager.listenToMatch(id,changed,()=>{$('loading-screen').textContent='Unable to read this room. Check the multiplayer Firestore rules.';screen('loading')})}
async function changed(m){if(!m)return menu('Room no longer available.');match=m;if(!single)localStorage.setItem(KEY,m.id);let classCode=PlatformManager.getClassCode(),questionType=m.settings?.questionType;if(!classCode)return menu('Return to the Hub and enter your own class code before joining a room.');if(!['matching','multichoice','category'].includes(questionType))return menu('This older room has no question format. Create a new room.');let k=classCode+':'+questionType;if(k!==bankKey){let r=await MultiplayerQuestionHelper.load({classCode,questionType});if(!r.ok)return menu('That question type is unavailable in your class question bank.');bankKey=k}if(m.status==='waiting'||m.status==='lobby'){$('room-code').textContent=m.roomCode;$('room-status').textContent=m.player2?'Both players joined. Press Ready.':'Waiting for opponent…';$('ready-btn').hidden=!m.player2;$('ready-btn').disabled=!!m.gameState.ready?.[me.uid];$('ready-btn').textContent=m.gameState.ready?.[me.uid]?'Ready ✓':'Ready';screen('room');return}if(m.status==='abandoned'){$('game-error').textContent=m.leftBy===me.uid?'You left the room.':'Opponent disconnected or left the room.';screen('game');disable(true);return}if(!session){PlatformManager.startSession(ID);session=true}screen('game');renderHud();questionGate();if(single)scheduleAI();if(m.status==='finished')result();if(m.gameState.lastShot?.id!==lastShotId){lastShotId=m.gameState.lastShot?.id;animateShot(m.gameState.lastShot)}}
function submit(change){return single?SinglePlayerManager.applyMove(me.uid,change):MultiplayerManager.submitMove(match.id,change)}
async function ready(){await submit((m,uid)=>{let ready={...(m.gameState.ready||{}),[uid]:true},both=m.player2&&ready[m.player1.uid]&&ready[m.player2.uid];if(!both)return{gameState:{...m.gameState,ready}};return{status:'playing',currentTurn:m.startingPlayerUid,gameState:{...m.gameState,ready,phase:'playing',turnGate:{uid:m.startingPlayerUid,status:'pending',nonce:Date.now()+''},turnDeadline:null}}})}
function side(uid,m=match){return m.player1.uid===uid?'p1':'p2'}function other(uid,m=match){return m.player1.uid===uid?m.player2.uid:m.player1.uid}function groundAt(x,state=match.gameState){return state.terrain[Math.max(0,Math.min(79,Math.floor(x/10)))]}
function islandHit(state,px,py){return (state.islands||[]).some(isl=>px>isl.x-isl.w/2&&px<isl.x+isl.w/2&&py>isl.y-isl.h/2&&py<isl.y+isl.h*0.6)}
function renderHud(){let mine=match.currentTurn===me.uid,gate=match.gameState.turnGate;$('turn-label').textContent=mine?(gate?.status==='passed'?'YOUR TURN':'ANSWER YOUR QUESTION'):(match.player1.uid===match.currentTurn?'PLAYER 1 TURN':'PLAYER 2 TURN');disable(!mine||gate?.status!=='passed'||match.status!=='playing');let p=match.gameState.players[side(me.uid)];Array.from($('weapon').options).forEach(o=>{let key=weapons[o.value].ammo,n=key?p.ammo[key]:null;o.disabled=key&&n<=0;o.textContent=o.value==='cannon'?'Cannon ∞':`${o.textContent.split(' ×')[0]} ×${n}`});$('result').hidden=match.status!=='finished'}
function disable(v){['left-btn','right-btn','angle','power','weapon','fire-btn','end-btn'].forEach(id=>$(id).disabled=v)}
function questionGate(){let g=match.gameState.turnGate;if(match.status!=='playing'||match.currentTurn!==me.uid||g?.status!=='pending'){$('question-overlay').hidden=true;questionNonce=null;return}if(questionNonce===g.nonce)return;questionNonce=g.nonce;question=MultiplayerQuestionHelper.next();if(!question)return;$('question-prompt').textContent=question.prompt;$('question-feedback').textContent='';$('question-options').innerHTML='';question.answers.forEach(a=>{let b=document.createElement('button');b.textContent=a.text;b.onclick=()=>answer(a.correct);$('question-options').appendChild(b)});$('question-overlay').hidden=false}
async function answer(correct){$('question-options').querySelectorAll('button').forEach(b=>b.disabled=true);MultiplayerQuestionHelper.record(question,correct);let bonuses=['heavy','triple','rocket','mega','heal','shield','move','damage'],bonus=correct?bonuses[Math.floor(Math.random()*bonuses.length)]:null;$('question-feedback').textContent=correct?'Correct! Bonus: '+bonus:'Incorrect — no combat bonus, but you may still take your turn.';await submit((m,uid)=>{let g=m.gameState.turnGate;if(m.currentTurn!==uid||g?.nonce!==questionNonce)return null;let players=structuredClone(m.gameState.players),p=players[side(uid,m)];if(bonus==='heal')p.hp=Math.min(100,p.hp+10);else if(bonus==='shield')p.shield=15;else if(['heavy','triple','rocket','mega'].includes(bonus))p.ammo[bonus]++;return{gameState:{...m.gameState,players,moveRemaining:bonus==='move'?140:80,damageBoost:bonus==='damage'?1.2:1,turnGate:{...g,status:'passed'},turnDeadline:Date.now()+20000}}})}
async function move(dx){try{await submit((m,uid)=>{if(m.currentTurn!==uid||m.gameState.turnGate?.status!=='passed')throw Error('NOT_TURN');let remaining=m.gameState.moveRemaining||0;if(Math.abs(dx)>remaining)return null;let players=structuredClone(m.gameState.players),p=players[side(uid,m)];p.x=Math.max(side(uid,m)==='p1'?20:420,Math.min(side(uid,m)==='p1'?380:780,p.x+dx));return{gameState:{...m.gameState,players,moveRemaining:remaining-Math.abs(dx)}}})}catch(e){$('game-error').textContent='Movement is unavailable.'}}
async function fire(){let angle=+$('angle').value,power=+$('power').value,weapon=$('weapon').value;try{await submit((m,uid)=>shotChanges(m,uid,angle,power,weapon))}catch(e){$('game-error').textContent=e.message}}
function shotChanges(m,uid,angle,power,weapon){if(m.currentTurn!==uid||m.gameState.turnGate?.status!=='passed')throw Error('Not your turn.');let state=structuredClone(m.gameState),key=weapons[weapon].ammo,actor=state.players[side(uid,m)];if(key&&actor.ammo[key]<=0)throw Error('No ammunition left.');if(key)actor.ammo[key]--;let dir=side(uid,m)==='p1'?1:-1,rad=angle*Math.PI/180,vx=Math.abs(Math.cos(rad))*power*dir,vy=-Math.abs(Math.sin(rad))*power,x=actor.x,y=groundAt(x,state)-18,path=[],hitGround=false;for(let t=0;t<8;t+=.08){let px=x+vx*t,py=y+vy*t+18*t*t;path.push([px,py]);if(px<0||px>W){x=Math.max(0,Math.min(W,px));y=Math.min(H,py);break}if(islandHit(state,px,py)){x=px;y=py;break}if(py>=groundAt(px,state)){x=px;y=Math.min(H,py);hitGround=true;break}}let cfg=weapons[weapon],players=state.players;Object.keys(players).forEach(k=>{let d=Math.hypot(players[k].x-x,groundAt(players[k].x,state)-y),damage=Math.max(0,Math.round(cfg.damage*(1-d/cfg.radius)*(state.damageBoost||1)));if(damage>0){let blocked=Math.min(players[k].shield||0,damage);players[k].shield-=blocked;players[k].hp=Math.max(0,players[k].hp-damage+blocked)}});if(hitGround){let centre=Math.floor(x/10),span=Math.ceil(cfg.radius/10);for(let i=Math.max(0,centre-span);i<=Math.min(79,centre+span);i++){let curve=Math.sqrt(Math.max(0,cfg.radius*cfg.radius-Math.pow(i*10-x,2)));state.terrain[i]=Math.min(H-15,Math.max(state.terrain[i],Math.round(y+curve*.55)))}}let winner=players.p1.hp<=0?m.player2.uid:players.p2.hp<=0?m.player1.uid:null,next=other(uid,m);state.lastShot={id:Date.now()+'-'+uid,path,impact:[x,y],weapon};state.damageBoost=1;state.moveRemaining=80;state.turnGate=winner?null:{uid:next,status:'pending',nonce:Date.now()+''};state.turnDeadline=null;return{gameState:state,status:winner?'finished':'playing',winner:winner,currentTurn:winner?null:next,rematchRequests:winner?{}:m.rematchRequests}}
function scheduleAI(){if(aiThinking||!single||match.status!=='playing'||match.currentTurn!==match.player2.uid)return;aiThinking=true;setTimeout(async()=>{try{await SinglePlayerManager.applyMove(match.player2.uid,(m,uid)=>{let test=structuredClone(m);test.gameState.turnGate={uid,status:'passed'};let actor=test.gameState.players[side(uid,test)],enemySide=side(other(uid,test),test),ownSide=side(uid,test);let available=Object.keys(weapons).filter(w=>!weapons[w].ammo||actor.ammo[weapons[w].ammo]>0),candidates=[];for(let weapon of available)for(let angle=20;angle<=80;angle+=10)for(let power=35;power<=95;power+=10){let outcome=shotChanges(test,uid,angle,power,weapon),enemyDamage=test.gameState.players[enemySide].hp-outcome.gameState.players[enemySide].hp,selfDamage=test.gameState.players[ownSide].hp-outcome.gameState.players[ownSide].hp;candidates.push({angle,power,weapon,score:enemyDamage*3-selfDamage*4})}candidates.sort((a,b)=>b.score-a.score);let accuracy=m.settings.aiProfile.averageAccuracy,strong=Math.random()<accuracy,pool=strong?candidates.filter(c=>c.score===candidates[0].score):candidates.slice(Math.min(2,candidates.length-1),Math.min(12,candidates.length));let pick=(pool.length?pool:candidates)[Math.floor(Math.random()*(pool.length||candidates.length))];return shotChanges(test,uid,pick.angle,pick.power,pick.weapon)})}finally{aiThinking=false}},700)}
async function endTurn(){if(!match||match.currentTurn!==me.uid)return;await submit((m,uid)=>{if(m.currentTurn!==uid)return null;let next=other(uid,m);return{currentTurn:next,gameState:{...m.gameState,moveRemaining:80,turnDeadline:null,turnGate:{uid:next,status:'pending',nonce:Date.now()+''}}}})}
function tick(){if(!match||match.status!=='playing')return;let d=match.gameState.turnDeadline;if(!d){$('timer').textContent='20';return}let left=Math.max(0,Math.ceil((d-Date.now())/1000));$('timer').textContent=left;if(left===0&&match.currentTurn===me.uid)endTurn();PlatformManager.heartbeat(ID,true)}
function result(){PlatformManager.endPracticeRun();let text=match.winner===me.uid?'YOU WIN!':'YOU LOSE';$('result-text').textContent=text;$('result').hidden=false;claim();let mine=match.rematchRequests?.[me.uid],opp=match.rematchRequests?.[other(me.uid)];$('rematch-btn').disabled=!single&&!!mine;$('rematch-status').textContent=single?'':mine?'Waiting for opponent…':opp?'Opponent wants a rematch.':''}
async function claim(){let key=match.id+':'+match.round;if(claiming.has(key))return;claiming.add(key);if(single){PlatformManager.recordMultiplayerResult(ID,match.winner===me.uid?'win':'loss');stats();return}let r=await MultiplayerManager.claimRoundReward(match.id,match.round);if(r){PlatformManager.recordMultiplayerResult(ID,r.result);stats()}}
async function rematch(){if(single){let state={...freshState(),phase:'playing'};SinglePlayerManager.rematch(state);return}await MultiplayerManager.requestRematch(match.id,{...freshState(),phase:'playing',ready:{[match.player1.uid]:true,[match.player2.uid]:true},turnGate:null})}
async function leave(){let id=matchId;if(stop){stop();stop=null}try{if(single)SinglePlayerManager.close();else if(id)await MultiplayerManager.leaveMatch(id)}catch(e){}menu()}
function menu(msg=''){localStorage.removeItem(KEY);match=null;matchId=null;single=false;if(session){PlatformManager.endSession(ID);session=false}$('menu-error').textContent=msg;screen('menu')}
function cloud(ctx,x,y,scale){ctx.fillStyle='rgba(255,255,255,.85)';ctx.beginPath();ctx.ellipse(x,y,22*scale,12*scale,0,0,Math.PI*2);ctx.ellipse(x+18*scale,y-6*scale,16*scale,10*scale,0,0,Math.PI*2);ctx.ellipse(x-18*scale,y-4*scale,14*scale,9*scale,0,0,Math.PI*2);ctx.fill();}
function drawIslands(ctx,state){(state.islands||[]).forEach(isl=>{let {x,y,w,h}=isl,gy=groundAt(x,state);ctx.fillStyle='rgba(10,10,30,.18)';ctx.beginPath();ctx.ellipse(x,gy+3,w*.32,6,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#8a7358';ctx.beginPath();ctx.ellipse(x,y+h*.15,w/2,h*.55,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#6b5843';for(let i=-1;i<=1;i++){ctx.beginPath();ctx.moveTo(x+i*w*.24,y+h*.5);ctx.lineTo(x+i*w*.24-5,y+h*.5+10+Math.abs(i)*5);ctx.lineTo(x+i*w*.24+5,y+h*.5+10+Math.abs(i)*5);ctx.closePath();ctx.fill()}ctx.fillStyle='#5fae4a';ctx.beginPath();ctx.ellipse(x,y-h*.28,w/2,h*.4,0,Math.PI,0);ctx.fill();ctx.fillStyle='#7fd464';ctx.beginPath();ctx.ellipse(x,y-h*.34,w/2*.88,h*.26,0,Math.PI,0);ctx.fill()})}
function drawTank(ctx,p,side,s){let y=groundAt(p.x,s)-16,dir=side==='p1'?1:-1;let body=side==='p1'?'#3ae4ff':'#ff5198',dark=side==='p1'?'#0c7f9c':'#9c0c48',light=side==='p1'?'#b8f7ff':'#ffc2dd';ctx.fillStyle='rgba(10,10,30,.25)';ctx.beginPath();ctx.ellipse(p.x,y+11,20,4,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#241f42';ctx.fillRect(p.x-16,y+1,32,8);ctx.fillStyle='#443b7a';for(let tx=-13;tx<=13;tx+=6)ctx.fillRect(p.x+tx,y+2,3,6);ctx.fillStyle=body;ctx.fillRect(p.x-15,y-10,30,12);ctx.fillStyle=dark;ctx.fillRect(p.x-15,y-10,30,3);ctx.fillStyle=light;ctx.fillRect(p.x-15,y-1,30,2);ctx.fillStyle=body;ctx.beginPath();ctx.arc(p.x,y-11,8,Math.PI,0);ctx.fill();ctx.fillStyle=dark;ctx.beginPath();ctx.arc(p.x,y-11,8,Math.PI*.15,Math.PI*.85);ctx.fill();ctx.strokeStyle=dark;ctx.lineWidth=4;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(p.x,y-12);ctx.lineTo(p.x+dir*17,y-22);ctx.stroke();if(p.shield>0){ctx.strokeStyle='#8ff0ff';ctx.lineWidth=2;ctx.globalAlpha=.7;ctx.beginPath();ctx.arc(p.x,y-6,22,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}ctx.fillStyle='#250b18';ctx.fillRect(p.x-25,y-33,50,6);ctx.fillStyle=p.hp>50?'#4cff72':p.hp>20?'#ffd23f':'#ff4d4d';ctx.fillRect(p.x-25,y-33,Math.max(0,p.hp/2),6);ctx.strokeStyle='#000';ctx.lineWidth=1;ctx.strokeRect(p.x-25,y-33,50,6);ctx.fillStyle='#fff';ctx.font='11px monospace';ctx.textAlign='center';ctx.fillText(p.hp+' HP',p.x,y-39);ctx.textAlign='left'}
function trajectory(state,x,dir,angle,power){let rad=angle*Math.PI/180,vx=Math.abs(Math.cos(rad))*power*dir,vy=-Math.abs(Math.sin(rad))*power,y=groundAt(x,state)-18,path=[];for(let t=0;t<8;t+=.08){let px=x+vx*t,py=y+vy*t+18*t*t;path.push([px,py]);if(px<0||px>W||py>=groundAt(px,state)||islandHit(state,px,py))break}return path}
function drawAimLine(ctx,s){if(!match||match.status!=='playing'||match.currentTurn!==me.uid||s.turnGate?.status!=='passed')return;let mySide=side(me.uid),actor=s.players[mySide],dir=mySide==='p1'?1:-1,angle=+$('angle').value,power=+$('power').value,path=trajectory(s,actor.x,dir,angle,power);if(!path.length)return;ctx.save();ctx.setLineDash([7,7]);ctx.lineWidth=2;ctx.strokeStyle='rgba(255,255,255,.7)';ctx.beginPath();path.forEach(([px,py],i)=>i===0?ctx.moveTo(px,py):ctx.lineTo(px,py));ctx.stroke();ctx.restore();let [lx,ly]=path[path.length-1];ctx.strokeStyle='#fff36d';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(lx-6,ly-6);ctx.lineTo(lx+6,ly+6);ctx.moveTo(lx+6,ly-6);ctx.lineTo(lx-6,ly+6);ctx.stroke()}
function draw(){let c=$('battlefield'),ctx=c?.getContext('2d');if(ctx){ctx.clearRect(0,0,W,H);let s=match?.gameState;if(s){let sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#55bfea');sky.addColorStop(1,'#d9ec9a');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff9c4';ctx.beginPath();ctx.arc(700,58,30,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.35;ctx.fillStyle='#fff3a0';ctx.beginPath();ctx.arc(700,58,44,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;cloud(ctx,120,68,1);cloud(ctx,330,48,.8);cloud(ctx,530,92,.65);ctx.fillStyle='#7fae6a';ctx.beginPath();ctx.moveTo(0,H);for(let i=0;i<=80;i++)ctx.lineTo(i*10,260+Math.sin(i/6)*18);ctx.lineTo(W,H);ctx.fill();ctx.fillStyle='#4f843c';ctx.beginPath();ctx.moveTo(0,H);s.terrain.forEach((y,i)=>ctx.lineTo(i*10,y));ctx.lineTo(W,H);ctx.fill();ctx.strokeStyle='#8fe07a';ctx.lineWidth=3;ctx.beginPath();s.terrain.forEach((y,i)=>i===0?ctx.moveTo(0,y):ctx.lineTo(i*10,y));ctx.stroke();drawIslands(ctx,s);drawAimLine(ctx,s);Object.entries(s.players).forEach(([k,p])=>drawTank(ctx,p,k,s))}}requestAnimationFrame(draw)}
const SHOT_STYLE={cannon:{color:'#fff36d',size:4,blast:45,blastColor:'#ffcf4d'},heavy:{color:'#ff9f43',size:5,blast:68,blastColor:'#ff7a1a'},triple:{color:'#7cf7ff',size:4,blast:34,blastColor:'#4fd8ff'},rocket:{color:'#ff5198',size:5,blast:30,blastColor:'#ff2e6d'},mega:{color:'#ff2e2e',size:7,blast:90,blastColor:'#ff5b5b'}};
function animateShot(shot){if(!shot)return;let c=$('battlefield'),ctx=c.getContext('2d'),i=0,style=SHOT_STYLE[shot.weapon]||SHOT_STYLE.cannon;function explode(pt,f){if(!match||f>14)return;let [x,y]=pt;ctx.save();ctx.globalAlpha=Math.max(0,1-f/14);ctx.fillStyle=style.blastColor;ctx.beginPath();ctx.arc(x,y,Math.max(2,style.blast*(f/14)),0,Math.PI*2);ctx.fill();ctx.restore();requestAnimationFrame(()=>explode(pt,f+1))}function frame(){if(!match)return;if(i<shot.path.length){let [x,y]=shot.path[i];ctx.save();ctx.shadowColor=style.color;ctx.shadowBlur=9;ctx.fillStyle=style.color;ctx.beginPath();ctx.arc(x,y,style.size,0,Math.PI*2);ctx.fill();ctx.restore();if(shot.weapon==='rocket'){ctx.fillStyle='rgba(255,255,255,.4)';ctx.beginPath();ctx.arc(x-5,y+2,3,0,Math.PI*2);ctx.fill()}i+=3;requestAnimationFrame(frame)}else{explode(shot.impact,0)}}frame()}
document.addEventListener('DOMContentLoaded',init);
})();
