(function(){'use strict';
const ID='pixel-artillery',KEY='arcadeAcademy.pixelArtillery.activeMatch',W=800,H=450,GROUND=390;
const $=id=>document.getElementById(id);let me,match,matchId,stop,question,questionNonce,bankKey,session=false,claiming=new Set(),lastShotId=null;
const weapons={cannon:{damage:34,radius:45,ammo:null},heavy:{damage:52,radius:68,ammo:'heavy'},triple:{damage:24,radius:34,ammo:'triple'},rocket:{damage:46,radius:30,ammo:'rocket'},mega:{damage:76,radius:90,ammo:'mega'}};
function terrain(){let a=[],y=310+Math.random()*35;for(let i=0;i<80;i++){y+=Math.random()*14-7;y=Math.max(245,Math.min(370,y));a.push(Math.round(y));}for(let i=0;i<8;i++){a[i]=330;a[71+i]=330;}return a;}
function freshState(){return{phase:'ready',terrain:terrain(),players:{p1:{x:85,hp:100,shield:0,ammo:{heavy:2,triple:2,rocket:2,mega:1}},p2:{x:715,hp:100,shield:0,ammo:{heavy:2,triple:2,rocket:2,mega:1}}},ready:{},moveRemaining:80,turnGate:null,turnDeadline:null,lastShot:null};}
function screen(name){['loading','menu','join','room','game'].forEach(n=>$(n+'-screen').hidden=n!==name)}
function stats(){let s=PlatformManager.getGameStats(ID)||{};$('wins').textContent=s.wins||0;$('losses').textContent=s.losses||0;$('draws').textContent=s.draws||0;$('games').textContent=s.gamesPlayed||0}
async function init(){bind();try{await MultiplayerManager.initialiseAuth();me=await MultiplayerManager.requirePlayer();stats();let saved=localStorage.getItem(KEY);if(saved&&/^\d{5}$/.test(saved))listen(saved);else screen('menu')}catch(e){$('loading-screen').innerHTML='<p>Sign in through the Arcade Academy Hub before playing online.</p><a href="../../index.html">Return to Hub</a>'}setInterval(tick,250);requestAnimationFrame(draw)}
function bind(){$('create-btn').onclick=create;$('show-join-btn').onclick=()=>screen('join');$('join-back').onclick=()=>screen('menu');$('join-form').onsubmit=join;$('room-input').oninput=e=>e.target.value=e.target.value.replace(/\D/g,'').slice(0,5);['leave-room-btn','leave-game-btn','result-leave'].forEach(id=>$(id).onclick=leave);$('ready-btn').onclick=ready;$('left-btn').onclick=()=>move(-20);$('right-btn').onclick=()=>move(20);$('end-btn').onclick=endTurn;$('fire-btn').onclick=fire;$('angle').oninput=e=>$('angle-out').textContent=e.target.value+'°';$('power').oninput=e=>$('power-out').textContent=e.target.value;$('rematch-btn').onclick=rematch}
async function create(){try{let classCode=PlatformManager.getClassCode(),questionType=$('question-type').value;if(!classCode)throw Error('Return to the Hub and enter your class code first.');let loaded=await MultiplayerQuestionHelper.load({classCode,questionType});if(!loaded.ok)throw Error('That question type is unavailable for this class.');matchId=await MultiplayerManager.createRoom(ID,freshState(),{classCode,questionType,requiresReady:true});localStorage.setItem(KEY,matchId);listen(matchId)}catch(e){$('menu-error').textContent=e.message}}
async function join(e){e.preventDefault();let code=$('room-input').value;if(!/^\d{5}$/.test(code)){$('join-error').textContent='Enter exactly five numbers.';return}try{matchId=await MultiplayerManager.joinRoom(code);localStorage.setItem(KEY,matchId);listen(matchId)}catch(err){$('join-error').textContent=err.message==='ROOM_NOT_FOUND'?'Room not found.':err.message==='ROOM_FULL'?'This room already has two players.':err.message}}
function listen(id){if(stop)stop();matchId=id;stop=MultiplayerManager.listenToMatch(id,changed,()=>{$('loading-screen').textContent='Unable to read this room. Check the multiplayer Firestore rules.';screen('loading')})}
async function changed(m){if(!m)return menu('Room no longer available.');match=m;localStorage.setItem(KEY,m.id);let k=m.settings?.classCode+':'+m.settings?.questionType;if(k!==bankKey){let r=await MultiplayerQuestionHelper.load(m.settings);if(!r.ok)return menu('Unable to load the room question bank.');bankKey=k}if(m.status==='waiting'||m.status==='lobby'){$('room-code').textContent=m.roomCode;$('room-status').textContent=m.player2?'Both players joined. Press Ready.':'Waiting for opponent…';$('ready-btn').hidden=!m.player2;$('ready-btn').disabled=!!m.gameState.ready?.[me.uid];$('ready-btn').textContent=m.gameState.ready?.[me.uid]?'Ready ✓':'Ready';screen('room');return}if(m.status==='abandoned'){$('game-error').textContent=m.leftBy===me.uid?'You left the room.':'Opponent disconnected or left the room.';screen('game');disable(true);return}if(!session){PlatformManager.startSession(ID);session=true}screen('game');renderHud();questionGate();if(m.status==='finished')result();if(m.gameState.lastShot?.id!==lastShotId){lastShotId=m.gameState.lastShot?.id;animateShot(m.gameState.lastShot)}}
async function ready(){await MultiplayerManager.submitMove(match.id,(m,uid)=>{let ready={...(m.gameState.ready||{}),[uid]:true},both=m.player2&&ready[m.player1.uid]&&ready[m.player2.uid];if(!both)return{gameState:{...m.gameState,ready}};return{status:'playing',currentTurn:m.startingPlayerUid,gameState:{...m.gameState,ready,phase:'playing',turnGate:{uid:m.startingPlayerUid,status:'pending',nonce:Date.now()+''},turnDeadline:null}}})}
function side(uid,m=match){return m.player1.uid===uid?'p1':'p2'}function other(uid,m=match){return m.player1.uid===uid?m.player2.uid:m.player1.uid}function groundAt(x,state=match.gameState){return state.terrain[Math.max(0,Math.min(79,Math.floor(x/10)))]}
function renderHud(){let mine=match.currentTurn===me.uid,gate=match.gameState.turnGate;$('turn-label').textContent=mine?(gate?.status==='passed'?'YOUR TURN':'ANSWER YOUR QUESTION'):(match.player1.uid===match.currentTurn?'PLAYER 1 TURN':'PLAYER 2 TURN');disable(!mine||gate?.status!=='passed'||match.status!=='playing');let p=match.gameState.players[side(me.uid)];Array.from($('weapon').options).forEach(o=>{let key=weapons[o.value].ammo,n=key?p.ammo[key]:null;o.disabled=key&&n<=0;o.textContent=o.value==='cannon'?'Cannon ∞':`${o.textContent.split(' ×')[0]} ×${n}`});$('result').hidden=match.status!=='finished'}
function disable(v){['left-btn','right-btn','angle','power','weapon','fire-btn','end-btn'].forEach(id=>$(id).disabled=v)}
function questionGate(){let g=match.gameState.turnGate;if(match.status!=='playing'||match.currentTurn!==me.uid||g?.status!=='pending'){$('question-overlay').hidden=true;questionNonce=null;return}if(questionNonce===g.nonce)return;questionNonce=g.nonce;question=MultiplayerQuestionHelper.next();if(!question)return;$('question-prompt').textContent=question.prompt;$('question-feedback').textContent='';$('question-options').innerHTML='';question.answers.forEach(a=>{let b=document.createElement('button');b.textContent=a.text;b.onclick=()=>answer(a.correct);$('question-options').appendChild(b)});$('question-overlay').hidden=false}
async function answer(correct){$('question-options').querySelectorAll('button').forEach(b=>b.disabled=true);MultiplayerQuestionHelper.record(question,correct);let bonuses=['heavy','triple','rocket','mega','heal','shield','move','damage'],bonus=correct?bonuses[Math.floor(Math.random()*bonuses.length)]:null;$('question-feedback').textContent=correct?'Correct! Bonus: '+bonus:'Incorrect — no combat bonus, but you may still take your turn.';await MultiplayerManager.submitMove(match.id,(m,uid)=>{let g=m.gameState.turnGate;if(m.currentTurn!==uid||g?.nonce!==questionNonce)return null;let players=structuredClone(m.gameState.players),p=players[side(uid,m)];if(bonus==='heal')p.hp=Math.min(100,p.hp+10);else if(bonus==='shield')p.shield=15;else if(['heavy','triple','rocket','mega'].includes(bonus))p.ammo[bonus]++;return{gameState:{...m.gameState,players,moveRemaining:bonus==='move'?140:80,damageBoost:bonus==='damage'?1.2:1,turnGate:{...g,status:'passed'},turnDeadline:Date.now()+20000}}})}
async function move(dx){try{await MultiplayerManager.submitMove(match.id,(m,uid)=>{if(m.currentTurn!==uid||m.gameState.turnGate?.status!=='passed')throw Error('NOT_TURN');let remaining=m.gameState.moveRemaining||0;if(Math.abs(dx)>remaining)return null;let players=structuredClone(m.gameState.players),p=players[side(uid,m)];p.x=Math.max(side(uid,m)==='p1'?20:420,Math.min(side(uid,m)==='p1'?380:780,p.x+dx));return{gameState:{...m.gameState,players,moveRemaining:remaining-Math.abs(dx)}}})}catch(e){$('game-error').textContent='Movement is unavailable.'}}
async function fire(){let angle=+$('angle').value,power=+$('power').value,weapon=$('weapon').value;try{await MultiplayerManager.submitMove(match.id,(m,uid)=>shotChanges(m,uid,angle,power,weapon))}catch(e){$('game-error').textContent=e.message}}
function shotChanges(m,uid,angle,power,weapon){if(m.currentTurn!==uid||m.gameState.turnGate?.status!=='passed')throw Error('Not your turn.');let state=structuredClone(m.gameState),key=weapons[weapon].ammo,actor=state.players[side(uid,m)];if(key&&actor.ammo[key]<=0)throw Error('No ammunition left.');if(key)actor.ammo[key]--;let dir=side(uid,m)==='p1'?1:-1,rad=angle*Math.PI/180,vx=Math.abs(Math.cos(rad))*power*dir,vy=-Math.abs(Math.sin(rad))*power,x=actor.x,y=groundAt(x,state)-18,path=[];for(let t=0;t<8;t+=.08){let px=x+vx*t,py=y+vy*t+18*t*t;path.push([px,py]);if(px<0||px>W||py>=groundAt(px,state)){x=Math.max(0,Math.min(W,px));y=Math.min(H,py);break}}let cfg=weapons[weapon],players=state.players;Object.keys(players).forEach(k=>{let d=Math.hypot(players[k].x-x,groundAt(players[k].x,state)-y),damage=Math.max(0,Math.round(cfg.damage*(1-d/cfg.radius)*(state.damageBoost||1)));if(damage>0){let blocked=Math.min(players[k].shield||0,damage);players[k].shield-=blocked;players[k].hp=Math.max(0,players[k].hp-damage+blocked)}});let centre=Math.floor(x/10),span=Math.ceil(cfg.radius/10);for(let i=Math.max(0,centre-span);i<=Math.min(79,centre+span);i++){let curve=Math.sqrt(Math.max(0,cfg.radius*cfg.radius-Math.pow(i*10-x,2)));state.terrain[i]=Math.min(H-15,Math.max(state.terrain[i],Math.round(y+curve*.55)))}let winner=players.p1.hp<=0?m.player2.uid:players.p2.hp<=0?m.player1.uid:null,next=other(uid,m);state.lastShot={id:Date.now()+'-'+uid,path,impact:[x,y],weapon};state.damageBoost=1;state.moveRemaining=80;state.turnGate=winner?null:{uid:next,status:'pending',nonce:Date.now()+''};state.turnDeadline=null;return{gameState:state,status:winner?'finished':'playing',winner:winner,currentTurn:winner?null:next,rematchRequests:winner?{}:m.rematchRequests}}
async function endTurn(){if(!match||match.currentTurn!==me.uid)return;await MultiplayerManager.submitMove(match.id,(m,uid)=>{if(m.currentTurn!==uid)return null;let next=other(uid,m);return{currentTurn:next,gameState:{...m.gameState,moveRemaining:80,turnDeadline:null,turnGate:{uid:next,status:'pending',nonce:Date.now()+''}}}})}
function tick(){if(!match||match.status!=='playing')return;let d=match.gameState.turnDeadline;if(!d){$('timer').textContent='20';return}let left=Math.max(0,Math.ceil((d-Date.now())/1000));$('timer').textContent=left;if(left===0&&match.currentTurn===me.uid)endTurn();PlatformManager.heartbeat(ID,true)}
function result(){let text=match.winner===me.uid?'YOU WIN!':'YOU LOSE';$('result-text').textContent=text;$('result').hidden=false;claim();let mine=match.rematchRequests?.[me.uid],opp=match.rematchRequests?.[other(me.uid)];$('rematch-btn').disabled=!!mine;$('rematch-status').textContent=mine?'Waiting for opponent…':opp?'Opponent wants a rematch.':''}
async function claim(){let key=match.id+':'+match.round;if(claiming.has(key))return;claiming.add(key);let r=await MultiplayerManager.claimRoundReward(match.id,match.round);if(r){PlatformManager.recordMultiplayerResult(ID,r.result);stats()}}
async function rematch(){await MultiplayerManager.requestRematch(match.id,{...freshState(),phase:'playing',ready:{[match.player1.uid]:true,[match.player2.uid]:true},turnGate:null})}
async function leave(){let id=matchId;if(stop){stop();stop=null}try{if(id)await MultiplayerManager.leaveMatch(id)}catch(e){}menu()}
function menu(msg=''){localStorage.removeItem(KEY);match=null;matchId=null;if(session){PlatformManager.endSession(ID);session=false}$('menu-error').textContent=msg;screen('menu')}
function draw(){let c=$('battlefield'),ctx=c?.getContext('2d');if(ctx){ctx.clearRect(0,0,W,H);let s=match?.gameState;if(s){let sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#55bfea');sky.addColorStop(1,'#d9ec9a');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='#4f843c';ctx.beginPath();ctx.moveTo(0,H);s.terrain.forEach((y,i)=>ctx.lineTo(i*10,y));ctx.lineTo(W,H);ctx.fill();Object.entries(s.players).forEach(([k,p])=>{let y=groundAt(p.x,s)-16;ctx.fillStyle=k==='p1'?'#3ae4ff':'#ff5198';ctx.fillRect(p.x-14,y-10,28,16);ctx.fillStyle='#222';ctx.fillRect(p.x-8,y-15,16,6);ctx.fillStyle='#250b18';ctx.fillRect(p.x-25,y-30,50,6);ctx.fillStyle='#4cff72';ctx.fillRect(p.x-25,y-30,p.hp/2,6);ctx.fillStyle='#fff';ctx.font='12px monospace';ctx.fillText(p.hp+' HP',p.x-20,y-36)})}}requestAnimationFrame(draw)}
function animateShot(shot){if(!shot)return;let c=$('battlefield'),ctx=c.getContext('2d'),i=0;function frame(){if(!match||i>=shot.path.length)return;let [x,y]=shot.path[i];ctx.fillStyle='#fff36d';ctx.fillRect(x-3,y-3,6,6);i+=3;requestAnimationFrame(frame)}frame()}
document.addEventListener('DOMContentLoaded',init);
})();
