window.GAME_CONFIG = {
  id: "pixel-artillery",
  title: "Thinking Tanks",
  name: "Thinking Tanks",
  description: "Command two selectable tanks against a class-calibrated computer or a live online opponent. Answer turn questions, cross destructible terrain and use six weapons—including a damage-free teleport shell.",
  catchphrase: "Answer. Aim. Fire!",
  genre: "Strategy / Artillery",
  gameModes: ["singleplayer", "multiplayer"],
  primaryMode: "multiplayer",
  players: "1 Player / 2 Online",
  questionType: "host-choice",
  version: "1.0.0",
  entry: "index.html",
  icon: "💥",
  requiresQuestionBank: true,
  supportsHighScores: false,
  supportsAchievements: true,
  createdBy: "Mr McKenzie",
  challengeMode:{enabled:false,types:{}}
};
